name: xhb4bio
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10.14
  - numpy=1.26.4
  - scipy=1.13.1
  - pandas=2.2.3
  - scikit-learn=1.4.0
  - matplotlib=3.8.4
  - numba=0.59.1
  - h5py=3.10.0
  - jupyter=1.0.0
  - jupyterlab=4.1.5
  - ipykernel=6.29.4
  - pillow=10.2.0
  - natsort=8.4.0
  - joblib=1.3.2
  - requests=2.31.0
  - certifi=2024.2.2
  - pip
  - scgpt
  - flash-attn<1.0.5
  - pip:
    # 这些建议用 pip 安装
    - scanpy==1.9.5
    - anndata==0.9.2
    - leidenalg==0.10.2
    - umap-learn==0.5.6
    - opencv-python==4.10.0.84
    - tifffile==2024.8.30
    - transformers==4.47.1
    - huggingface-hub==0.27.0
    - safetensors==0.4.5
    - segment-anything==1.0
    - squidpy==1.6.1
    - spatialdata==0.2.5.post0